### ISSUE TITLE
Meqtrees: NameError [name 'im' is not defined]

### ISSUE THREAD

**Issue by kamva1** [ratt-ru/meqtrees#888]
so this happens when I am running the meqtrees simulation script. (e.g python sim_time.py). This is on both ike and jake (python 2.7_. see the output below:

```
'root namespace is', '__main__', None)
2022/06/08 11:01:30 PYXIS: ===[ Pyxis: Python eXtensions for Inteferometry Scripting (C) 2013 by Oleg Smirnov <oms@ska.ac.za> ]===
2022/06/08 11:01:30 PYXIS: VERBOSE=1 by default
2022/06/08 11:01:30 PYXIS: loading Pyxis into context '__main__'
2022/06/08 11:01:30 PYXIS: registered module 'mqt'
2022/06/08 11:01:30 PYXIS: registered module 'std'
2022/06/08 11:01:30 PYXIS: executing '/usr/bin/which casapy':
2022/06/08 11:01:30 WARNING: /usr/bin/which returned error code 1
2022/06/08 11:01:30 PYXIS: executing '/usr/bin/which casa':
2022/06/08 11:01:30 PYXIS: /usr/bin/which succeeded
2022/06/08 11:01:30 PYXIS: registered module 'ms'
2022/06/08 11:01:30 PYXIS: registered module 'imager'
2022/06/08 11:01:30 PYXIS: registered module 'im'
Warning: No Cattery package found.
If you have Cattery in a non-standard location, please set the MEQTREES_CATTERY_PATH environment
variable to point to it.
2022/06/08 11:01:30 PYXIS: registered module 'im.argo'
2022/06/08 11:01:30 PYXIS: registered module 'lsm'
2022/06/08 11:01:31 PYXIS: executing '/usr/bin/time meqtree-pipeliner.py --mt 2 -c tdlconf.profiles [Sim_source_radius] gridded_sky.source_flux=1.0 gridded_sky.grid_m0=0.0 ms_sel.msname=MeerKAT_Hires.MS_p0 turbo-sim.py =_tdl_job_1_simulate_MS':
### Starting meqserver
('### Attaching to configuration file', 'tdlconf.profiles')
('### Loading config section', 'Sim_source_radius')
### Setting option gridded_sky.source_flux=1.0
### Setting option gridded_sky.grid_m0=0.0
### Setting option ms_sel.msname=MeerKAT_Hires.MS_p0
('### Compiling', 'turbo-sim.py')
### (using previously set options)
  (Meow.MSUtils: found /usr/bin/lwimager, can use it for imaging.)
  (Meow.MSUtils: found image viewer /usr/bin/tigger)
  (Meow.MSUtils: found image viewer /usr/bin/kvis)
  (Meow.MSUtils: found image viewer /usr/bin/ds9)
Successful readonly open of autonoread-locked table MeerKAT_Hires.MS_p0: 25 columns, 151200 rows
Successful readonly open of autonoread-locked table /home/vanqa/Vanqa/Vanqa/MeerKAT_Hires.MS_p0/ANTENNA: 8 columns, 27 rows
Successful readonly open of default-locked table /home/vanqa/Vanqa/Vanqa/MeerKAT_Hires.MS_p0/OBSERVATION: 9 columns, 1 rows
Successful readonly open of autonoread-locked table /home/vanqa/Vanqa/Vanqa/MeerKAT_Hires.MS_p0/POLARIZATION: 4 columns, 1 rows
Successful readonly open of autonoread-locked table /home/vanqa/Vanqa/Vanqa/MeerKAT_Hires.MS_p0/DATA_DESCRIPTION: 3 columns, 1 rows
Successful readonly open of autonoread-locked table /home/vanqa/Vanqa/Vanqa/MeerKAT_Hires.MS_p0/SPECTRAL_WINDOW: 14 columns, 1 rows
Successful readonly open of autonoread-locked table /home/vanqa/Vanqa/Vanqa/MeerKAT_Hires.MS_p0/FIELD: 9 columns, 1 rows
  (Meow.MSUtils: found /usr/bin/lwimager, can use it for imaging.)
  (Meow.MSUtils: found image viewer /usr/bin/tigger)
  (Meow.MSUtils: found image viewer /usr/bin/kvis)
  (Meow.MSUtils: found image viewer /usr/bin/ds9)
Using LSM module from Tigger (1.4.2) 1.4.2 at /usr/lib/python2.7/dist-packages/Tigger (in path)
Successful readonly open of default-locked table MeerKAT_Hires.MS_p0: 25 columns, 151200 rows
Successful readonly open of default-locked table MeerKAT_Hires.MS_p0: 25 columns, 151200 rows
Successful readonly open of default-locked table MeerKAT_Hires.MS_p0: 25 columns, 151200 rows
Successful readonly open of default-locked table MeerKAT_Hires.MS_p0: 25 columns, 151200 rows
('### ', 'TDL script successfully compiled. 1414 node definitions\n  (of which 3 are root nodes) sent to meqserver.')
### Running TDL job "_tdl_job_1_simulate_MS"
Meow.ReadVisHeader
('### Job result:', None)
### Stopping the meqserver
### All your batch are belong to us. Bye!
28.27user 12.20system 0:30.24elapsed 133%CPU (0avgtext+0avgdata 416892maxresident)k
0inputs+3402200outputs (0major+298714minor)pagefaults 0swaps
2022/06/08 11:02:01 PYXIS: meqtree-pipeliner.py succeeded
Visibility column shape: (151200, 360, 4)
Successful readonly open of default-locked table /home/vanqa/Vanqa/Vanqa/MeerKAT_Hires.MS_p0/SPECTRAL_WINDOW: 14 columns, 1 rows
2022/06/08 11:02:33 PYXIS: registered module 'im.lwimager'
Traceback (most recent call last):
  File "sim_time.py", line 138, in <module>
    sim_now()
  File "sim_time.py", line 124, in sim_now
    weight = "natural")#,basename_image='sim_img_%d.fits'%k, dirty_image = 'sim_img_%d.fits'%k);
  File "/usr/lib/python2.7/dist-packages/Pyxides/imager.py", line 92, in make_image
    call_imager = eval( 'im.%s.make_image'%(imager.lower()) )
  File "<string>", line 1, in <module>
NameError: name 'im' is not defined

``` 
@o-smirnov

**Comment by o-smirnov** [comment]
@kamva1, once again, full sequence of commands please, from the moment you log in.

**Comment by kamva1** [comment]
On server ike : I go inside my working directory (e.g cd vanqa/Vanqa/Vanqa) -- here I have all the files and scripts I am using to run my main script (sim_time.py). Then I run on the working directory( python sim_time.py) and when running this, I get the above error.

**Comment by kamva1** [comment]
@o-smirnov Please find this on  **ike**: ```/home/vanqa/Vanqa/Vanqa/sim_time.py```

 with all other scripts imported into this one.

**Comment by bennahugo** [comment]
I've set up a reproducer here based on the input. I had to port the scripts to python3 for this with minor modifications. It looks like the imager module of pyxis no longer works as intended -- don't think this is part of the test as far as I know:
The scripts are here:
(venv) hugo@jake:~/mtbuild/test-vanqa$ 

You should activate ~/mtbuild/venv for the python3 build of MT

You can then run his sim_time.py script.

which yields the same error as the system packages above:
```
('### Job result:', None)
### Stopping the meqserver
### All your batch are belong to us. Bye!
11.49user 6.55system 0:16.61elapsed 108%CPU (0avgtext+0avgdata 178664maxresident)k
0inputs+9488outputs (0major+105126minor)pagefaults 0swaps
2022/06/08 15:06:57 PYXIS: meqtree-pipeliner.py succeeded
Visibility column shape: (151200, 1, 4)
Successful readonly open of default-locked table /home/hugo/mtbuild/test-vanqa/MeerKAT_hires.MS/SPECTRAL_WINDOW: 14 columns, 1 rows
Saved plot to Pyplots0.png
2022/06/08 15:06:57 PYXIS: registered module 'im.lwimager'
Traceback (most recent call last):
  File "sim_time.py", line 152, in <module>
    sim_now()
  File "sim_time.py", line 138, in sim_now
    weight = "natural")#,basename_image='sim_img_%d.fits'%k, dirty_image = 'sim_img_%d.fits'%k);
  File "/home/hugo/mtbuild/venv/lib/python3.6/site-packages/Pyxides/imager.py", line 92, in make_image
    call_imager = eval( 'im.%s.make_image'%(imager.lower()) )
  File "<string>", line 1, in <module>
NameError: name 'im' is not defined

```

**Comment by bennahugo** [comment]
I suggest porting this issue over to pyxis. It is not a meqtrees problem per say
